### PR TITLE
Return ownership for all candidate moves

### PR DESCRIPTION
**Pull request by sanderland**
This includes the ownership map in all 'moveInfos' objects for the analysis engine.

Probably needs some cleaning up and could be optimized, but opening this PR to see if you're interested in including this.
I'm using it to experiment with 'simple moves' AIs on the front-end side.

### CODE REVIEW

**Comment by lightvector** [comment]
Yeah, seems plausible. Yeah, maybe would be good to do in a way that factors out some of the logic into a common function and worth thinking about optimization and avoiding duplicating work with main ownership and the amount of data sent back. But I could certainly see adding this option.

**Comment by sanderland** [comment]
Cleaned it up a bit, factored out formatting function and such, and introduced a documented option for doing this.
Had a look at if the root+children ownership could easily be retrieved in one go, and found the answer to be no, probably not worth introducing bugs over premature optimization.

**Comment by lightvector** [comment]
Merged, along with a few additional cleanups in 656414c8

Thanks!

**Comment by lightvector** [comment]
Including, if it matters, one slight change to the semantics - the per-move ownership option no longer implies the root ownership option. They're just independent options now.

**Pull request merged**
