### PR TITLE
Replace Board reference with just board size

### PR DESCRIPTION
**Pull request by nerai**
Avoid duplicate work,
Simplify calculations,
Reduce dependencies.

### CODE REVIEW

**Comment by nerai** [comment]
Good idea, I'll push an update.

**Comment by lightvector** [comment]
Don't mean to nitpick, but it should be sqrtBoardArea instead of sqrtSideLength, right? Like, when the board is 10 x 16, this value will be equal to sqrt(160), rather than equal to the square root of either of the side lengths, sqrt(10) or sqrt(16).

**Comment by nerai** [comment]
Oops, my bad. Sorry! Fixed.

**Comment by lightvector** [comment]
Looks great, thanks!

**Pull request merged**
