### PR TITLE
Workaround CMake 3.17.0 (Bug? Errata? API Change?) with handling CUDA…

### PR DESCRIPTION
**Pull request by OmnipotentEntity**
… compiler testing

See issue #225 for details, and thanks @cleinias for the patch

### CODE REVIEW

**Comment by OmnipotentEntity** [comment]
I should note that this PR has been tested and seems to work on older versions of CMake as well.

**Comment by lightvector** [comment]
Thanks. I'll try it myself soon.

**Comment by OmnipotentEntity** [comment]
To be clear, I think this is a bug in CMake, and I'm not necessarily expecting this patch to be accepted.  Rather, I think eventually CMake will fix this issue, and this patch will not be necessary.

I'm submitting this patch for review specifically because NixOS has a policy that any patches made against upstream should be submitted to the maintainers, and not kept out of band.

I expect the next time a katago release comes around this patch won't actually be needed.

**Comment by OmnipotentEntity** [comment]
CMake tracking issue: https://gitlab.kitware.com/cmake/cmake/-/issues/20708

**Comment by OmnipotentEntity** [comment]
Per CMake devs, this is a better workaround, and probably the proper way of making CUDA shared.

See [this comment in the tracking issue for a rundown.](https://github.com/lightvector/KataGo/issues/225#issuecomment-630246169)

**Comment by OmnipotentEntity** [comment]
Fixed this specificity of the version.  This should now work for everyone.

**Comment by suyoung-park** [comment]
Dear sir


I want to contact you. But I don't know how. So I write here
 

We are one of the broadcasting channel in Korea, specialized in Baduk(=GO), 

which is called ‘KBaduk’.

 

We want to provide winning-rate graphs to our viewers when we broadcast, 

using your ‘KataGo (Copyright 2019 David J Wu ("lightvector")’ system.

Of course, we will notate <Sources from KataGo> at the bottom of the graphs.

 

You've told me when using KataGo, it was mentioned that “Permission is granted including without limitation 

the right to use, copy, modify, merge, publish, distribute,sublicense, and/or sell copies of the Software”, 

 

However KBaduk want to use KataGo with your permission. 

Is it able to use KataGo and notate that the source is from KataGo when we broadcast? 

I am looking forward to your reply. 

If you can't reply here, please send an email to l psypassion@gmail.com 

Take care of yourself.


Yours sincerely.

**Comment by lightvector** [comment]
@suyoung-park - Sounds cool. I'm replying to you privately. In the future, if you want to post a new question, please make a new separate issue (Issues -> New Issue), rather than posting in an issue or pull request that is unrelated to your topic.

**Comment by lightvector** [comment]
Maybe it's not needed now, and mabe this is a bit late, but I merged it anyways in case anyone in the future lands on one of these cmake versions. I think Github didn't auto detect it though, due me also doing a manual rebase, so I'm going ahead to just close this. Thanks!

**Pull request closed without merging**
