### PR TITLE
Fix movesOwnership on symmetric boards in GTP

### LINKED ISSUE #616: movesOwnership on symmetric boards
Some suggested moves have the exactly same movesOwnership in symmetric cases. This seems unreasonable. (missing flip/rotation?)

~~~
$ git log --oneline -n 1
0d30fab9 (HEAD -> master, upstream/master) Fix indentation, add pvEdgeVisits param, update docs
~~~

For example,

~~~
      8  -0.0828751 -0.0732991 -0.0591904 -0.0530779 -0.0371
~~~

means that the same "movesOwnership -0.0828751 ..." is repeated 8 times in the next case.

~~~
$ (echo "play B K10\nshowboard\nkata-analyze 100 movesOwnership true"; sleep 3) \
  | ./katago-cpu gtp \
  | ruby -pe '$_.gsub!(/info.*?movesOwnership/, "\n")' \
  | uniq -c | head -n 40 | cut -c1-60
KataGo v1.10.0
Using TrompTaylor rules initially, unless GTP/GUI overrides this
Initializing board with boardXSize 19 boardYSize 19
Loaded config /XXX/YYY/katago/default_gtp.cfg
Loaded model /XXX/YYY/katago/default_model.bin.gz
Model name: g170-b10c128-s1141046784-d204142634
GTP ready, beginning main protocol loop
      1 = 
      1 
      1 = MoveNum: 1 HASH: 7BC546600F28A10FEF906A96B1D6386D
      1    A B C D E F G H J K L M N O P Q R S T
      1 19 . . . . . . . . . . . . . . . . . . .
      1 18 . . . . . . . . . . . . . . . . . . .
      1 17 . . . . . . . . . . . . . . . . . . .
      1 16 . . . . . . . . . . . . . . . . . . .
      1 15 . . . . . . . . . . . . . . . . . . .
      1 14 . . . . . . . . . . . . . . . . . . .
      1 13 . . . . . . . . . . . . . . . . . . .
      1 12 . . . . . . . . . . . . . . . . . . .
      1 11 . . . . . . . . . . . . . . . . . . .
      1 10 . . . . . . . . . X1. . . . . . . . .
      1  9 . . . . . . . . . . . . . . . . . . .
      1  8 . . . . . . . . . . . . . . . . . . .
      1  7 . . . . . . . . . . . . . . . . . . .
      1  6 . . . . . . . . . . . . . . . . . . .
      1  5 . . . . . . . . . . . . . . . . . . .
      1  4 . . . . . . . . . . . . . . . . . . .
      1  3 . . . . . . . . . . . . . . . . . . .
      1  2 . . . . . . . . . . . . . . . . . . .
      1  1 . . . . . . . . . . . . . . . . . . .
      1 Next player: White
      1 Rules: {"friendlyPassOk":false,"hasButton":false,"ko
      1 B stones captured: 0
      1 W stones captured: 0
      1 
      1 =
      1 
      8  -0.0828751 -0.0732991 -0.0591904 -0.0530779 -0.0371
      4  -0.0703164 -0.0629292 -0.0540418 -0.0512431 -0.0589
      8  -0.0418649 -0.0304599 -0.0183639 -0.0282922 -0.0408
      8  -0.0537984 -0.0349631 -0.0497077 -0.0571987 -0.0561
      4  0.000349155 -0.000250136 -0.0043722 -0.0196525 -0.0
      8  -0.0481416 -0.0209728 -0.010267 -0.0190256 -0.01967
      8  0.0186746 0.0175947 0.00381822 0.00368366 -0.000598
      8  -0.0124514 -0.0184028 0.00886869 0.0131375 0.003276
      8  -0.0192767 -0.00547164 -0.000930537 -0.0050424 -0.0
      4  0.0265487 0.0347454 0.0169129 0.0285222 0.029918 0.
~~~

I got 2 repetitions in the next case.

~~~
$ (echo "play B D10\nshowboard\nkata-analyze 100 movesOwnership true"; sleep 3) \
  | ./katago-cpu gtp \
  | ruby -pe '$_.gsub!(/info.*?movesOwnership/, "\n")' \
  | uniq -c | head -n 40 | cut -c1-60
      1 = 
      1 
      1 = MoveNum: 1 HASH: 6E811E1FB0AE4B44AD535C42B451F165
      1    A B C D E F G H J K L M N O P Q R S T
      1 19 . . . . . . . . . . . . . . . . . . .
      1 18 . . . . . . . . . . . . . . . . . . .
      1 17 . . . . . . . . . . . . . . . . . . .
      1 16 . . . . . . . . . . . . . . . . . . .
      1 15 . . . . . . . . . . . . . . . . . . .
      1 14 . . . . . . . . . . . . . . . . . . .
      1 13 . . . . . . . . . . . . . . . . . . .
      1 12 . . . . . . . . . . . . . . . . . . .
      1 11 . . . . . . . . . . . . . . . . . . .
      1 10 . . . X1. . . . . . . . . . . . . . .
      1  9 . . . . . . . . . . . . . . . . . . .
      1  8 . . . . . . . . . . . . . . . . . . .
      1  7 . . . . . . . . . . . . . . . . . . .
      1  6 . . . . . . . . . . . . . . . . . . .
      1  5 . . . . . . . . . . . . . . . . . . .
      1  4 . . . . . . . . . . . . . . . . . . .
      1  3 . . . . . . . . . . . . . . . . . . .
      1  2 . . . . . . . . . . . . . . . . . . .
      1  1 . . . . . . . . . . . . . . . . . . .
      1 Next player: White
      1 Rules: {"friendlyPassOk":false,"hasButton":false,"ko
      1 B stones captured: 0
      1 W stones captured: 0
      1 
      1 =
      1 
      2  -0.230287 -0.227813 -0.210048 -0.179005 -0.108889 -
      2  -0.176155 -0.208192 -0.226433 -0.211374 -0.169249 -
      2  0.0692858 0.0411489 0.00636274 0.00874555 0.0009290
      2  0.0612116 0.0459546 0.0313492 0.0437271 0.039156 0.
      2  -0.236252 -0.222346 -0.221098 -0.18874 -0.148462 -0
      2  -0.0781834 -0.0419933 -0.0445152 -0.0509469 -0.0587
      2  0.0783258 0.0543027 0.0211263 0.0206058 0.0112802 -
      2  -0.048051 -0.0477857 -0.0268424 -0.0288938 -0.03077
      2  -0.1552 -0.139086 -0.106085 -0.0947755 -0.110391 -0
      1  -0.127485 -0.0815903 -0.044629 -0.102357 -0.0659088
~~~

No repetition in the next asymmetric case.

~~~
$ (echo "play B D3\nshowboard\nkata-analyze 100 movesOwnership true"; sleep 3) \
  | ./katago-cpu gtp \
  | ruby -pe '$_.gsub!(/info.*?movesOwnership/, "\n")' \
  | uniq -c | head -n 40 | cut -c1-60
      1 = 
      1 
      1 = MoveNum: 1 HASH: 399178EAA13E7B3665350D3C481B629B
      1    A B C D E F G H J K L M N O P Q R S T
      1 19 . . . . . . . . . . . . . . . . . . .
      1 18 . . . . . . . . . . . . . . . . . . .
      1 17 . . . . . . . . . . . . . . . . . . .
      1 16 . . . . . . . . . . . . . . . . . . .
      1 15 . . . . . . . . . . . . . . . . . . .
      1 14 . . . . . . . . . . . . . . . . . . .
      1 13 . . . . . . . . . . . . . . . . . . .
      1 12 . . . . . . . . . . . . . . . . . . .
      1 11 . . . . . . . . . . . . . . . . . . .
      1 10 . . . . . . . . . . . . . . . . . . .
      1  9 . . . . . . . . . . . . . . . . . . .
      1  8 . . . . . . . . . . . . . . . . . . .
      1  7 . . . . . . . . . . . . . . . . . . .
      1  6 . . . . . . . . . . . . . . . . . . .
      1  5 . . . . . . . . . . . . . . . . . . .
      1  4 . . . . . . . . . . . . . . . . . . .
      1  3 . . . X1. . . . . . . . . . . . . . .
      1  2 . . . . . . . . . . . . . . . . . . .
      1  1 . . . . . . . . . . . . . . . . . . .
      1 Next player: White
      1 Rules: {"friendlyPassOk":false,"hasButton":false,"ko
      1 B stones captured: 0
      1 W stones captured: 0
      1 
      1 =
      1 
      1  -0.00721945 -0.00110021 -0.00311642 -0.00446483 -0.
      1  -0.0626003 -0.0652198 -0.0700732 -0.0618177 -0.0652
      1  0.155205 0.117162 0.0832747 0.1058 0.0881641 0.0694
      1  0.0932111 0.093413 0.079373 0.0527796 0.0337743 0.0
      1  -0.0185139 -0.00828627 0.000986327 -0.012138 -0.027
      1  0.0342009 0.0527674 0.0488542 0.0518982 0.0206366 -
      1  0.379947 0.35072 0.29632 0.181487 0.0614014 -0.0125
      1  -0.138953 -0.126359 -0.110955 -0.109679 -0.0921399 
      1  0.381325 0.40109 0.427947 0.405954 0.330283 0.19978
      1  -0.0583389 -0.0443852 -0.041846 -0.0216825 -0.04131
~~~

### PR DESCRIPTION
**Pull request by kaorahi**
Fix #616. This is just a shameless copy from getJsonOwnershipAndStdevMap except for roundStatic. :)

### CODE REVIEW

**Comment by lightvector** [comment]
Let's factor out the code then instead of having it twice. Since AnalysisData has the symmetry recorded, maybe it should be a method of AnalysisData (analysisdata.h) to take as input the ownership vector and return the ownershipToOutput vector, and then both places can call that code?

**Comment by kaorahi** [comment]
Thanks for the quick reply. Yes, duplicated code is ugly.

I'm willing to rewrite my patch if it helps you. But I'm afraid it may increase your work actually and delay the release as I know nothing about C++. So please feel free to close this PR if you like to do the refactoring quickly by yourself. :)

**Comment by lightvector** [comment]
No problem, I will do it. Thanks!

**Comment by kaorahi** [comment]
See also 901822a9 for missing outer `if(... || ...)`.

**Comment by lightvector** [comment]
Done, pushed to master.

**Comment by kaorahi** [comment]
thx! 21b4efef works fine.

**Pull request closed without merging**
